language: node_js
node_js:
  - "10"
before_script:
  - npm i
script: npm run prepublish
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
env:
  - REACT=16
notifications:
  email:
    - email:edwardfhsiao@gmail.com
